name: OTP Bot Deployment

on:
  push:
    branches:
      - main  # Runs the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9 (you can change this to the version you need)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Verify Python Installation
      run: |
        python --version  # Check Python version
        pip show flask  # Ensure Flask is installed
        pip show python-telegram-bot  # Ensure python-telegram-bot is installed

    - name: Run the OTP bot
      run: |
        # Run the script in the background and redirect output to log
        nohup python otp_bot.py > otp_bot.log 2>&1 &
        sleep 10  # Wait for Flask app to start
        # Output the last 50 lines of the log file to check for errors
        tail -n 50 otp_bot.log

        # Check if Flask app is running by curling the local server
        curl http://localhost:5000 || (echo "Flask app is not running. Exiting." && exit 1)
