name: OTP Bot Deployment

on:
  push:
    branches:
      - main  # Runs the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9 (you can change this to the version you need)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run the OTP bot
      run: |
        nohup python otp_bot.py > otp_bot.log 2>&1 &  # Run the script in the background and log output to otp_bot.log
        sleep 10  # Wait 10 seconds for the Flask app to start
        cat otp_bot.log  # Show the last 20 lines of the log to diagnose issues
        curl http://localhost:5000 || (echo "Flask app is not running" && exit 1)  # Test if the Flask app is running, exit if it fails

