    - name: Run the OTP bot
      run: |
        # Run the script with the correct filename handling
        nohup python3 "payment OTP.py" > otp_bot.log 2>&1 &
        sleep 10  # Wait for Flask app to start
        # Output the last 50 lines of the log file to check for errors
        tail -n 50 otp_bot.log

        # Check if Flask app is running by curling the local server
        curl http://localhost:5000 || (echo "Flask app is not running. Exiting." && exit 1)
