name: OTP Bot Deployment

on:
  push:
    branches:
      - main  # Runs the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9 (you can change this to the version you need)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt (you'll need to create this file)

    - name: Run the OTP bot
      run: |
        nohup python otp_bot.py &  # Run the script in the background
        sleep 5  # Allow a few seconds for the script to start
        curl http://localhost:5000  # Test if the Flask app is running
        
